### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'has_key'

### ISSUE THREAD

**Issue by Puriney** [navinlabcode/CNV_pipeline#21]
```
1056208 reads; of these:
  1056208 (100.00%) were unpaired; of these:
    37652 (3.56%) aligned 0 times
    754109 (71.40%) aligned exactly 1 time
    264447 (25.04%) aligned >1 times
96.44% overall alignment rate
Traceback (most recent call last):
  File "/volumes/seq/code/PIPELINES/CNA_pipeline_v1.4/bin/varbin.sam.2.py", line 152, in <module>
    main()
  File "/volumes/seq/code/PIPELINES/CNA_pipeline_v1.4/bin/varbin.sam.2.py", line 12, in main
    chrominfo = fileToDictionary(sys.argv[4], 0)
  File "/volumes/seq/code/PIPELINES/CNA_pipeline_v1.4/bin/varbin.sam.2.py", line 122, in fileToDictionary
    if rd.has_key(id):
AttributeError: 'dict' object has no attribute 'has_key'
```
 It keeps giving those errors and in the end it gives:

```
Illegal division by zero at /volumes/seq/code/PIPELINES/CNA_pipeline_v1.4/bin/All_stat_metrics.pl line 66.
Illegal division by zero at /volumes/seq/code/PIPELINES/CNA_pipeline_v1.4/bin/All_stat_metrics_summary.pl line 66.
here() starts at /volumes/lab/users/yyan/project/map_g_and_t
Warning message:
In readLines(f, n) : line 1 appears to contain an embedded nul
```

Any idea?

**Comment by Puriney** [comment]
Should I use some specific version of Python?

**Comment by darlanminussi** [comment]
@Puriney Hi Yun, yes, the pipeline is only compatible with python2, python 3 does not work
@MinBio  There is a dictionary call that is the issue which was removed from python 2 to python3, we can correct based on @Puriney error log. It's a simple fix

**Comment by MinBio** [comment]
Ok. fixed. it should be working for both python 3 and 2
